spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/zebvo_ai
spring.datasource.username=root
spring.datasource.password=root

openrouter.api.key=${OPENROUTER_API_KEY}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
